spring.datasource.url=jdbc:mysql://localhost:3306/coding_tracker
spring.datasource.username=root
spring.datasource.password=Raghav@0103
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=YOUR_JWT_SECRET_HERE
pring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
erver.port=8080